name = "NEIME_2019"
description = ""
doi = ""
source = ""
xref = ""

[assays_meta]
file_path = "assays.csv"
sequence_feature = "sequence"
engineering_round_feature = ""
split_feature = ""
split_strategy = ""
columns = [ "DMS_score", "sequence",]

[structures_meta]
file_path = "structure"

[assays_meta.assays.DMS_score]
description = ""
features = []

[assays_meta.assays.DMS_score.constants]
