site_name: ProteinGym Base Documentation
theme:
  name: material
  logo: images/proteingymlogo.png
  favicon: images/proteingymlogo.png

plugins:
- search
- mkdocs-autoapi:
    autoapi_add_nav_entry: Code Reference
    autoapi_dir: src
    autoapi_ignore:
      - "**/__about__.py"
      - "**/__main__.py"
- mkdocstrings:
    handlers:
      python:
        paths: [src]
- mkdocs-jupyter

nav:
- Home: index.md
- Manifest: manifest.md
- ADRs: decisions/
- Tutorials:
  - Introduction: notebooks/01_Introduction_to_PG2_Dataset.ipynb
  - Creating a manifest: notebooks/02_Creating_Manifests_and_Archives.ipynb
  - Loading data: notebooks/03_Loading_and_Accessing_Data.ipynb
  - Using pgdata for ML: notebooks/04_Data_Access_for_ML.ipynb

