[project]
name = "pg2-dataset"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tintinrevient", email = "zhaobenben007@googlemail.com" }
]
dynamic = ["version"]  # Dynamically set hatch version using git tags
classifiers = ["Private :: Do Not Upload"]  # Do not upload to public PYPI (by accident)
requires-python = ">=3.12"
dependencies = [
    "cloudpathlib[gs,s3]>=0.21.0",
    "polars[pyarrow]>=1.30.0",
    "pandas==2.2.3",
    "pydantic>=2.11.4",
    "toml>=0.10.2",
    "biopython>=1.85",
    "msgpack>=1.1.0",
]

[project.scripts]
pg2-dataset = "pg2_dataset.__main__:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyterlab>=4.4.1",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.2.1",
    "ruff>=0.11.7",
]

[tool.hatch.version]
path = "src/pg2_dataset/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/pg2_dataset"]

[tool.pytest.ini_options]
testpaths = ["tests", "README.md"]
addopts = "--doctest-modules --doctest-glob='*.md' --cov=pg2_dataset --cov-branch --cov-report xml --cov-fail-under=80"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["N805"]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "N", # pep8 naming
    "I", # isort
    # "C", # flake8-comprehensions
    "B", # flake8-bugbear
]
