[project]
name = "proteingym-base"
description = "Infrastructure for protein variant effect prediction. Dataset class and tools to facilitate benchmarking."
readme = "README.md"
authors = [  
    { name = "ProteinGym team", email = "proteingym@googlegroups.com" }  
]  
dynamic = ["version"]  # Dynamically set hatch version using git tags
classifiers = ["Private :: Do Not Upload"]  # Do not upload to public PYPI (by accident)
requires-python = ">=3.12"
dependencies = [
    "typer>=0.16.0,<1.0.0",
    "toml>=0.10.2,<1.0.0",
    "pydantic>=2.11.4,<3.0.0",
    "semver>=3.0.4,<4.0.0",
    "biopython>=1.85.0,<2.0.0",
    "msgpack>=1.1.0,<2.0.0",
    "polars[pyarrow]>=1.30.0,<2.0.0",
    "python-frontmatter>=1.1.0",
    "scikit-learn>=1.5.0,<2.0.0",
    "pandas>=2.3.3",
]

[project.scripts]
proteingym-base = "proteingym.base.__main__:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyterlab>=4.4.1",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.2.1",
    "ruff>=0.11.7",
    "scikit-learn>=1.7.2",
    "mkdocs-material",
    "mkdocstrings-python",
    "mkdocs-autoapi", 
]

[tool.hatch.version]
path = "src/proteingym/base/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/proteingym/"]

[tool.pytest.ini_options]
testpaths = ["tests", "README.md", "src"]
addopts = "--doctest-modules --doctest-glob='*.md' --cov=proteingym.base --cov-branch --cov-report xml --cov-fail-under=80"
filterwarnings = [
    'ignore:.*Aggregation applied.*:UserWarning',
]
[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["N805"]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "N", # pep8 naming
    "I", # isort
    # "C", # flake8-comprehensions
    "B", # flake8-bugbear
    "A", # flake8-builtins
]

[tool.ruff.lint.pep8-naming]
extend-ignore-names = ["X"]