# TODO: Should this be moved inside the ../example_data/NEIME_2019 folder?
name = "NEIME_2019"

[[ assays ]]
path = "../example_data/NEIME_2019/Assays/Assay1.csv"
target = "DMS_score"
sequence = "mutated_sequence"

[[ structures ]]
path = "../example_data/NEIME_2019/Structures/experimental.cif"

[[ msas ]]
path = "../example_data/NEIME_2019/MSA/msa.a2m"
format = "fasta"