name = "NEIME_2019"

[assays_meta]
file_path = "example_data/NEIME_2019/Assays/Assay1.csv"
columns = ["mutated_sequence", "mutant", "DMS_score", "DMS_score_bin", "split", "engineering_round"]
sequence_feature = "mutated_sequence"
split_feature="split"
engineering_round_feature="engineering_round"

[structures_meta]
file_path = "/Users/vanderweg/Projects/PG2/pg2-dataset/example_data/NEIME_2019/Structures/experimental.cif"

[msa_meta]
file_path = "/Users/vanderweg/Projects/PG2/pg2-dataset/example_data/NEIME_2019/MSA/msa.a2m"
file_format = "fasta"
gap_chars = ["."]

[assays_meta.assays.DMS_score]