name = "PG2-Dataset"
description = "This is an example dataset"
version = "1.0"


[[ sequences ]]
sequence_type = "wild_type"
sequence_alphabet = "DNA"

[ sequences.sources ]
local = ["example_data/NEIME_2019/sequences"]
