[artifacts]
records = "example_data/v1/A0A1I9GEU1_NEIME_Kennouche_2019/sequences.csv" # or uri
structure = "example_data/v1/A0A1I9GEU1_NEIME_Kennouche_2019/structure.cif"
# msa = "data/msa.npy"

[records]
sequence_feature = "mutated_sequence"
columns = ["mutated_sequence", "mutant", "DMS_score", "DMS_score_bin"]
schemas = ["pl.String", "pl.String", "pl.Float32", "pl.Float32"]

# [metadata]
# name = "project name"
# description = "project description"
# doi = "DOI: 10.1000/xyz123"
# source = "DOI: 10.1000/xyz123"
# xref = ?

# [assays]
# [assay.one]
# target = "target_name"

# features = ["feature1", "feature2"]

# TODO -> add hierarchy of constants
# arbitrary_constant1 = "arbitrary value 1"
# arbitrary_constant2 = "arbitrary value 2"

# [assay.two]
# target = "target_name"
