[resources]
records = "https://github.com/ProteinGym2/dvc-dataset-registry/protein_gym/A0A1I9GEU1_NEIME_Kennouche_2019.csv"

[records]
sequence_feature = "mutated_sequence"
split_strategy = "RandomSplitStrategy"
split_strategy_kwargs = {train_ratio = 0.8, valid_ratio = 0.1}

[records.assays.DMS_score]
features = ["mutated_sequence"]

[enums]
split_strategies = ["RandomSplitStrategy"]
